version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: omibus_local_django
    container_name: omibus_local_django
    volumes:
      - .:/app:z
    ports:
      - '8000:8000'
    command: /start

  docs:
    image: omibus_local_docs
    container_name: omibus_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    volumes:
      - ./docs:/docs:z
    ports:
      - '9000:9000'
    command: /start-docs