version: "3.8"

volumes:
  omibus_local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: omibus_local_django
    container_name: omibus_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: omibus_local_postgres
    container_name: omibus_local_postgres
    volumes:
      - omibus_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: omibus_local_docs
    container_name: omibus_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    volumes:
      - ./docs:/docs:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: omibus_local_redis
