version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: omibus_local_django
    container_name: omibus_local_django
    volumes:
      - .:/app:z
    ports:
      - '8000:8000'
    command: /start