# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define single executor for all jobs.
# See: https://circleci.com/docs/configuration-reference/#executors
executors:
  docker:
    docker:
      - image: cimg/base:2023.09

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker compose -f local.yml build
      - run: docker compose -f local.yml run --rm django python manage.py migrate
      - run: docker compose -f local.yml run --rm django python manage.py test

  test:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker compose -f local.yml build
      - run: docker compose -f local.yml run --rm django python manage.py pre-commit run -a

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  dev:
    jobs:
      - lint
      - test
